"""Английские переводы видимых строк (anime_vault\\i18n.py). Ключ — русская строка из кода, как есть;
{поля} в переводе — те же, что в оригинале (tests\\test_i18n.py это проверяет)."""

EN = {
    # ---- общее и консоль
    "ОШИБКА": "ERROR",
    "Что сделать": "What to do",
    "Нажмите Enter, чтобы продолжить…": "Press Enter to continue…",
    "Ответьте одной буквой: {letters}": "Answer with one letter: {letters}",
    "Остановлено (Ctrl+C). Всё сделанное сохранено — можно запустить снова.": "Stopped (Ctrl+C). Everything done so far is saved — you can run it again.",
    "непредвиденный сбой программы (подробности ниже)": "unexpected program failure (details below)",
    "пришлите текст ниже разработчику; запуск ещё раз безопасен — сделанное не теряется": "send the text below to the developer; running again is safe — nothing done is lost",
    "Готово. Нажмите Enter, чтобы закрыть окно…": "Done. Press Enter to close the window…",
    "Да": "Yes",
    "Нет": "No",
    "проверка": "test",
    "уже идёт другая команда": "another command is already running",

    # ---- manifest
    "пустой адрес": "empty address",
    "это ссылка на пин или страницу Pinterest, а не на доску — откройте доску и скопируйте её адрес": "this is a link to a pin or a Pinterest page, not to a board — open the board and copy its address",
    "короткая ссылка pin.it — откройте её в браузере и скопируйте полный адрес доски": "a short pin.it link — open it in the browser and copy the full board address",
    "не похоже на адрес — вставьте ссылку целиком (https://…)": "this does not look like an address — paste the whole link (https://…)",
    "не найден {manifest} ни в {start}, ни выше": "{manifest} not found in {start} or above",
    "запускайте .bat-файлы из папки коллекции (там, где лежит {manifest}), или передайте --root": "run the .bat files from the collection folder (where {manifest} is), or pass --root",
    "{path} — ошибка JSON: {error}": "{path} — JSON error: {error}",
    "проверьте запятые и кавычки (пути — с прямыми слэшами /)": "check commas and quotes (paths use forward slashes /)",
    "проверьте запятые и кавычки": "check commas and quotes",
    "нет папки коллекции {root}": "the collection folder {root} does not exist",
    "укажите папку коллекции в «Настройках»": "set the collection folder in Settings",
    "у доски «{name}» нет адреса": "board “{name}” has no address",
    "впишите ссылку на доску в «Настройках»": "enter the board link in Settings",
    "не хватает параметра {name} ({path} или {settings})": "missing setting {name} ({path} or {settings})",
    "сравните с anime-paths.example.json и config.example.json в проекте": "compare with anime-paths.example.json and config.example.json in the project",

    # ---- browsers
    "Куки из файла — браузер закрывать не нужно": "Cookies from a file — no need to close the browser",
    "Без входа — только публичные доски": "Not signed in — public boards only",

    # ---- download
    "текст не вшит в {name}: {error}": "text not embedded into {name}: {error}",
    "браузер": "the browser",
    "не удалось расшифровать куки браузера {browser}": "could not decrypt the cookies of {browser}",
    "новые Chrome / Edge не отдают куки другим программам — сохраните cookies.txt расширением браузера и укажите файл в «Настройках» (или войдите через Firefox)": "recent Chrome / Edge do not share cookies with other programs — save cookies.txt with a browser extension and choose the file in Settings (or sign in with Firefox)",
    "не удалось прочитать куки браузера": "could not read the browser cookies",
    "полностью закройте {browser} (и в трее тоже) и запустите снова": "fully close {browser} (including the tray icon) and run again",
    "сайт не пускает к доске (403 / приватная)": "the site denies access to the board (403 / private)",
    "войдите на сайт в браузере {browser} под своим аккаунтом, закройте браузер и запустите снова": "sign in to the site in {browser} with your account, close the browser and run again",
    "доска не найдена (404)": "board not found (404)",
    "проверьте ссылку на доску в «Настройках» — скопируйте её из адресной строки браузера": "check the board link in Settings — copy it from the browser address bar",
    "gallery-dl не умеет качать с этого адреса": "gallery-dl cannot download from this address",
    "проверьте ссылку; список сайтов — github.com/mikf/gallery-dl, docs/supportedsites.md": "check the link; supported sites — github.com/mikf/gallery-dl, docs/supportedsites.md",
    "сайт ограничил запросы (слишком часто)": "the site is rate limiting (too many requests)",
    "подождите 15–30 минут и запустите снова — скачанное не потеряется": "wait 15–30 minutes and run again — nothing downloaded is lost",
    "нет связи с сайтом": "cannot reach the site",
    "проверьте интернет (и обходчик блокировок, если он нужен) и запустите снова": "check your internet connection (and VPN / proxy if you need one) and run again",
    "gallery-dl завершился с ошибкой (текст выше)": "gallery-dl failed (see the text above)",
    "запустите снова — уже скачанное не качается повторно": "run again — files already downloaded are not downloaded twice",
    "Куки прочитаны — {browser} можно снова открыть.": "Cookies read — you can open {browser} again.",
    "скачано {count}: {name}": "downloaded {count}: {name}",
    "Скачивание нового с досок": "Downloading new files from boards",
    "Доски: {boards}": "Boards: {boards}",
    "Куда:  {target}": "To:     {target}",
    "Перед началом:": "Before you start:",
    "1. Откройте {browser} и убедитесь, что вы вошли на сайт (аккаунт с этими досками).": "1. Open {browser} and make sure you are signed in to the site (the account with these boards).",
    "2. Полностью закройте {browser} (и значок в трее) — иначе куки не прочитать.": "2. Fully close {browser} (and its tray icon) — otherwise the cookies cannot be read.",
    "3. Нажмите Enter здесь. Когда начнётся скачивание первой доски, браузер можно снова открыть.": "3. Press Enter here. Once the first board starts downloading, you can open the browser again.",
    "Готово? Нажмите Enter…": "Ready? Press Enter…",
    "Готово": "Ready",
    "{browser} ещё запущен. Закройте его полностью (проверьте трей) и нажмите Enter снова.": "{browser} is still running. Close it completely (check the tray) and press Enter again.",
    "не установлен gallery-dl": "gallery-dl is not installed",
    "в папке проекта выполните: venv\\Scripts\\pip install -r requirements.txt": "in the project folder run: venv\\Scripts\\pip install -r requirements.txt",
    "не задано ни одной доски": "no boards configured",
    "добавьте ссылки на доски в «Настройках»": "add board links in Settings",
    "у доски «{name}» не указан пользователь Pinterest": "board “{name}” has no Pinterest user",
    "впишите в «Настройках» полную ссылку на доску или пользователя Pinterest": "enter the full board link or the Pinterest user in Settings",
    "Собираю, что уже есть (dataN и источники раскладки), чтобы не качать повторно…": "Collecting what is already there (dataN and distribution sources) to skip it…",
    "{folder}: файлов {count}": "{folder}: {count} files",
    "известных файлов {known}, новых записей в архиве gallery-dl {added}": "{known} known files, {added} new entries in the gallery-dl archive",
    "{board}: доразобран прошлый запуск — новых {moved}, дублей {duplicates}": "{board}: finished the previous run — {moved} new, {duplicates} duplicates",
    "Доска «{board}»: скачиваю новое…": "Board “{board}”: downloading new files…",
    "Доска «{board}»: новых файлов {moved}": "Board “{board}”: {moved} new files",
    ", дублей отброшено {count}": ", {count} duplicates skipped",
    ", без вшитого текста {count}": ", {count} without embedded text",
    "часть файлов сайт не отдал — они докачаются при следующем запуске": "the site did not return some files — they will be fetched on the next run",
    "доска «{board}»: {what}": "board “{board}”: {what}",
    "Итог": "Summary",
    "{board}: новых {count}": "{board}: {count} new",
    "Не докачаны: {boards} — исправьте причину выше и запустите снова.": "Not finished: {boards} — fix the cause above and run again.",
    "Готово. Новое лежит в папках досок; разложить по пачкам — «Разложить» в окне или distribute.bat.": "Done. New files are in the board folders; to split them into batches use Distribute in the window or distribute.bat.",

    # ---- distribute
    "Раскладка нового по dataN": "Distributing new files into dataN",
    "Собираю, что уже есть в dataN и test-dataN…": "Collecting what is already in dataN and test-dataN…",
    "Ищу новое в источниках…": "Looking for new files in the sources…",
    "{source}: новых {found}, дублей {dup}": "{source}: {found} new, {dup} duplicates",
    "Нового нет — раскладывать нечего.": "Nothing new — nothing to distribute.",
    "План": "Plan",
    "data{number}: {count} файлов": "data{number}: {count} files",
    "дубли: {count} → duplicates (удалить вручную после просмотра)": "duplicates: {count} → duplicates (delete after review)",
    "Перенести?": "Move the files?",
    "Отменено — ничего не перенесено.": "Cancelled — nothing was moved.",
    "{folder}: перенесено {count}": "{folder}: {count} moved",
    "дубли перенесены в {folder}": "duplicates moved to {folder}",
    "Готово: {count} файлов в {folders} папках (data{first}…data{last}).": "Done: {count} files in {folders} folders (data{first}…data{last}).",
    "Дальше — anime-sort: prepare.bat подхватит новые папки.": "Next — anime-sort: prepare.bat will pick up the new folders.",

    # ---- окно: каркас
    "Обзор": "Overview",
    "Скачать": "Download",
    "Разложить": "Distribute",
    "Дубли": "Duplicates",
    "Настройки": "Settings",
    "Доски → пачки": "Boards → batches",
    "Команда не идёт": "No command running",
    "Журнал": "Log",
    "Остановить": "Stop",
    "Очистить": "Clear",
    "Здесь будет вывод команд. Вопросы команд появятся кнопками под журналом.": "Command output appears here. Questions from a command appear as buttons below the log.",
    "Что скачано, что ждёт раскладки, папки dataN": "What is downloaded, what waits for distribution, dataN folders",
    "Скачать новое": "Download new",
    "Доски → папки досок (gallery-dl, вход через куки браузера)": "Boards → board folders (gallery-dl, signed in with browser cookies)",
    "Разложить по dataN": "Distribute into dataN",
    "Новое из источников → папки dataN по размеру пачки, дубли — в duplicates": "New files from the sources → dataN folders of the batch size, duplicates → duplicates",
    "Что раскладка не стала класть в dataN: такой же файл уже есть в коллекции": "Files distribution did not put into dataN: the same file is already in the collection",
    "config.json рядом с программой — личное, не в git": "config.json next to the program — personal, not in git",

    # ---- окно: обзор
    "Ждёт раскладки": "Waiting",
    "Папок dataN": "dataN folders",
    "На досках": "On boards",
    "Дубли на просмотр": "Duplicates to review",
    "Что дальше": "Next steps",
    "Открыть коллекцию": "Open collection",
    "Обновить": "Refresh",
    "≈ {folders} папок по {size}": "≈ {folders} folders of {size}",
    "Всё разложено": "Everything is distributed",
    "Последняя {name}": "Last: {name}",
    "Пока нет": "None yet",
    "хранится": "kept",
    "Страница «Дубли» — посмотреть и удалить": "See the Duplicates page to review and delete",
    "Последняя раскладка: {journal}": "Last distribution: {journal}",
    "Раскладок ещё не было": "No distributions yet",
    "{date} {time} — перенесено {count}": "{date} {time} — {count} moved",
    "Коллекция не найдена: укажи её папку в «Настройках»": "Collection not found: set its folder in Settings",

    # ---- окно: скачать
    "Перед началом": "Before you start",
    "Проверяю браузер…": "Checking the browser…",
    "Начать скачивание": "Start download",
    "Доски": "Boards",
    "Открой {browser} и проверь, что вошёл на сайт — в аккаунт с этими досками.": "Open {browser} and check that you are signed in — to the account with these boards.",
    "Полностью закрой {browser}, вместе со значком в трее: у открытого браузера куки не прочитать.": "Fully close {browser}, including the tray icon: cookies of a running browser cannot be read.",
    "Нажми «Начать скачивание». Когда начнётся первая доска, браузер можно снова открыть.": "Click “Start download”. Once the first board starts, you can open the browser again.",
    "Проверь, что в {browser} выполнен вход на сайт — в аккаунт с этими досками.": "Check that you are signed in to the site in {browser} — to the account with these boards.",
    "Нажми «Начать скачивание» — {browser} можно не закрывать.": "Click “Start download” — no need to close {browser}.",
    "Куки берутся из файла cookies.txt — проверь, что он свежий (сохранён после входа на сайт).": "Cookies come from cookies.txt — make sure it is fresh (saved after signing in).",
    "Нажми «Начать скачивание».": "Click “Start download”.",
    "Вход не настроен — скачаются только публичные доски (приватные — в «Настройках» выбери браузер).": "Sign-in is not set up — only public boards will download (for private ones choose a browser in Settings).",
    "{browser} открыт — закрой его полностью": "{browser} is open — close it completely",
    "{browser} закрыт — можно начинать": "{browser} is closed — ready to start",

    # ---- окно: разложить
    "Источники — ждут раскладки": "Sources — waiting for distribution",
    "Точный план покажет сама команда: она отсеет дубли (тот же пин или та же картинка уже есть в dataN / test-dataN) и спросит «Перенести?». Файлы ПЕРЕНОСЯТСЯ, дубли — в duplicates.": "The command shows the exact plan: it filters out duplicates (the same pin or image already in dataN / test-dataN) and asks before moving. Files are MOVED, duplicates go to duplicates.",
    "{count} файлов → около {folders} папок: data{first}…data{last} по {size}.": "{count} files → about {folders} folders: data{first}…data{last}, {size} each.",
    "Раскладывать нечего — сначала скачайте новое.": "Nothing to distribute — download something new first.",

    # ---- окно: дубли
    "Открыть папку": "Open folder",
    "Всё в Корзину": "All to Recycle Bin",
    "Ищу дубли…": "Looking for duplicates…",
    "Дублей: {count}": "Duplicates: {count}",
    "Дублей нет — всё чисто.": "No duplicates — all clean.",
    "Показать ещё ({count})": "Show more ({count})",
    "Дубль": "Duplicate",
    "Оригинал": "Original",
    "Нет файла": "No file",
    "Откуда: {path}": "From: {path}",
    "Оригинал: {path}": "Original: {path}",
    "Оригинал: не записан в журнале (раскладка старой версии) или уже удалён": "Original: not in the journal (older version) or already deleted",
    "В Корзину": "To Recycle Bin",
    "Открыть": "Open",
    "Оригинал в папке": "Show original",
    "Не картинка": "Not an image",
    "Отправить в Корзину все дубли ({count})? Их можно будет восстановить из Корзины.": "Send all duplicates ({count}) to the Recycle Bin? They can be restored from there.",
    "В Корзину отправлено дублей: {count}": "Duplicates sent to the Recycle Bin: {count}",

    # ---- окно: команды
    "Скачивание": "Download",
    "Раскладка": "Distribution",
    "Уже идёт другая команда — дождись её или останови.": "Another command is running — wait for it or stop it.",
    "Коллекция не найдена — укажи папку в «Настройках».": "Collection not found — set the folder in Settings.",
    "Идёт: {title}": "Running: {title}",
    "Готово — браузер закрыт": "Ready — browser is closed",
    "Продолжить": "Continue",
    "Команда завершена.": "Command finished.",
    "Команда завершилась с ошибкой (код {code}).": "Command failed (code {code}).",
    "Остановлено. Всё сделанное сохранено — можно запустить снова.": "Stopped. Everything done so far is saved — you can run it again.",

    # ---- окно: настройки
    "Общее": "General",
    "Язык / Language": "Language / Язык",
    "Окно перезапустится на выбранном языке": "The window restarts in the chosen language",
    "Папка коллекции": "Collection folder",
    "Куда всё качается и где лежат пачки dataN (anime-paths.json — для связки с anime-sort, не обязателен)": "Where everything is downloaded and where dataN batches live (anime-paths.json is only for anime-sort, optional)",
    "Раскладывать новое по пачкам dataN": "Distribute new files into dataN batches",
    "Выключено — anime-vault только скачивает, страница «Разложить» скрыта": "Off — anime-vault only downloads, the Distribute page is hidden",
    "Файлов в одной dataN": "Files per dataN",
    "Последняя папка может быть меньше": "The last folder may be smaller",
    "Вход на сайт": "Signing in",
    "Куки": "Cookies",
    "Opera / Firefox — надёжно; новые Chrome и Edge шифруют куки — для них лучше файл cookies.txt": "Opera / Firefox work reliably; recent Chrome and Edge encrypt cookies — use a cookies.txt file with them",
    "Профиль / файл": "Profile / file",
    "Пользователь Pinterest": "Pinterest user",
    "Подставится сам из первой ссылки на доску (pinterest.com/<имя>/<доска>)": "Filled in from the first board link (pinterest.com/<user>/<board>)",
    "Куда качать": "Download to",
    "Относительно папки коллекции; по папке на доску": "Relative to the collection folder; one folder per board",
    "Вставь ссылку на доску Pinterest (или на что угодно, что качает gallery-dl: Danbooru, Pixiv, X …) — имя папки подставится само.": "Paste a link to a Pinterest board (or to anything gallery-dl supports: Danbooru, Pixiv, X …) — the folder name is filled in for you.",
    "Доска": "Board",
    "Сохранить": "Save",
    "Выбрать…": "Browse…",
    "Файл cookies.txt": "cookies.txt file",
    "Без входа (публичные доски)": "Not signed in (public boards)",
    "Путь к cookies.txt (формат Netscape) — сохрани его расширением браузера после входа на сайт": "Path to cookies.txt (Netscape format) — export it with a browser extension after signing in",
    "Не нужно": "Not needed",
    "Папка профиля, например …/AppData/Roaming/Opera Software/Opera GX Stable; пусто — обычная Opera": "Profile folder, e.g. …/AppData/Roaming/Opera Software/Opera GX Stable; empty — regular Opera",
    "Пусто — профиль по умолчанию; или папка профиля": "Empty — default profile; or a profile folder",
    "Папка (имя доски)": "Folder (board name)",
    "Ссылка на доску — https://…": "Board link — https://…",
    "Только хранить": "Keep only",
    "Только хранить — не раскладывается": "Keep only — not distributed",
    "Укажи существующую папку коллекции.": "Choose an existing collection folder.",
    "Размер пачки — целое число больше нуля.": "Batch size must be a whole number above zero.",
    "Доска «{address}»: {error}": "Board “{address}”: {error}",
    "Две доски с одной папкой «{name}» — переименуй одну.": "Two boards use the folder “{name}” — rename one.",
    "Файл куки не найден: {path}": "Cookie file not found: {path}",
    "Сохранено в config.json.": "Saved to config.json.",
    "Язык сохранён — применится, когда закончится команда и окно откроется заново.": "Language saved — it applies after the command finishes and the window is reopened.",
}
